services:
  app:
    user: "www-data"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html                       # Bind mount, viditeľný vo windowse
      - app_storage:/var/www/html/storage     # Named volume, zostáva po docker-compose down (treba -v na zmazanie)
      - /var/www/html/bootstrap/cache         # Anonymné volume (zmaže sa pri down)
    ports:
      - "${HTTP_PORT}:80"
    networks:
      - dpb_network
    depends_on:
      - db
      - redis
      - node
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dpb
      DB_USERNAME: dpb
      DB_PASSWORD: dpb
      REDIS_HOST: redis

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_DATABASE: dpb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dpb
      MYSQL_PASSWORD: dpb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dpb_network
  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    networks:
      - dpb_network

  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_node
    working_dir: /var/www/html
    volumes:
      - node_modules:/var/www/html/node_modules
    networks:
      - .:/var/www/html
      - dpb_network
    ports:
      - "${VITE_PORT}:5173"
    command: [ "sh", "-c", "[ ! -d node_modules ] && npm install; npm run dev" ]

networks:
  dpb_network:
    name: ${COMPOSE_PROJECT_NAME}_network

volumes:
  app_storage:
    name: ${COMPOSE_PROJECT_NAME}_app_storage
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
  node_modules:
    name: ${COMPOSE_PROJECT_NAME}_node_modules
