services:
  app:
    user: "www-data"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html                                           # Bind mount, viditeľný vo windowse
      - ${COMPOSE_PROJECT_NAME}_app_storage:/var/www/html/storage # Named volume, zostáva po docker-compose down (treba -v na zmazanie)
      - /var/www/html/bootstrap/cache                             # Anonymné volume (zmaže sa pri down)
    ports:
      - "8080:80"
    networks:
      - ${COMPOSE_PROJECT_NAME}_network
    depends_on:
      - db
      - redis
      - node
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dpb
      DB_USERNAME: dpb
      DB_PASSWORD: dpb
      REDIS_HOST: redis

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_DATABASE: dpb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dpb
      MYSQL_PASSWORD: dpb
    ports:
      - "3307:3306"
    volumes:
      - ${COMPOSE_PROJECT_NAME}_db_data:/var/lib/mysql
    networks:
      - ${COMPOSE_PROJECT_NAME}_network
  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    networks:
      - ${COMPOSE_PROJECT_NAME}_network

  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_node
    working_dir: /var/www/html
    volumes:
      - ${COMPOSE_PROJECT_NAME}_node_modules:/var/www/html/node_modules
    networks:
      - ${COMPOSE_PROJECT_NAME}_network
    ports:
      - "5173:5173"
    command: [ "sh", "-c", "[ ! -d node_modules ] && npm install; npm run dev" ]

networks:
  ${COMPOSE_PROJECT_NAME}_network:

volumes:
  ${COMPOSE_PROJECT_NAME}_app_storage:
  ${COMPOSE_PROJECT_NAME}_db_data:
  ${COMPOSE_PROJECT_NAME}_node_modules:
